apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lakekeeper
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Lakekeeper
    gethomepage.dev/group: Data Engineering
    gethomepage.dev/description: Data Catalog
    gethomepage.dev/icon: lakekeeper.png
    gethomepage.dev/pod-selector: ""
spec:
  parentRefs:
    - name: http
      namespace: gateway-system
  hostnames:
    - "lakekeeper.southcity.dev"
  rules:
    - backendRefs:
        - name: lakekeeper
          port: 8181
