apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  servar.app: qbittorrent

configMapGenerator:
- name: qbittorrent-conf
  literals:
  - PUID=1000
  - PGID=1000
  - TZ=Europe/Oslo
  - WEBUI_PORT=8080
  - TORRENTING_PORT=6881

secretGenerator:
- name: gluetun-secrets
  env: .env

resources:
- pvc.yml
- deployment.yml
- service.yml
