apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pocket-id-operator
spec:
  interval: 5m
  url: oci://ghcr.io/aclerici38/charts/pocket-id-operator
  ref:
    semver: ~0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-operator
spec:
  releaseName: pocket-id-operator
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
  values:
    instance:
      spec:
        encryptionKey:
          valueFrom:
            secretKeyRef:
              name: pocket-id-encryption-key
              key: encryption-key
        appUrl: "https://pocket-id-operator.southcity.dev"
        route:
          enabled: true
          name: pocket-id-operator
          parentRefs:
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: http
              namespace: kgateway-system
