apiVersion: v1
kind: Secret
metadata:
  name: csi-s3
type: Opaque
stringData:
  values.yaml: ENC[AES256_GCM,data:pUHNu7YDrY0kAWzR7KIu8JVRTZsTGKDgedGzati1q6wZNHSoAZ6ymeEP/tFz4liwcs0FY9m0L4LsOQ0DSQk98cmJ+hqPGZrNyg6AAGahxbNO4/rLVjNBt2oYmawiqC7bGQLKodBXyCHs+2myOszER47N1dQ3GPB5bcXJn9NlyRvjxlQNiH0p+CFNcEI/KOyRzRl72fMHYgL16q0+0ohFlNlKCWtDzfqKO9yXDSZ2sqE7d0wYINfruIasY3v5q14u05BFu5kEEUpxBtaPzGOMkwR4uDMe,iv:Ka75hcHU3tasIde5A33W7w5zZeL8SQhQPa2C0LAREpo=,tag:MKSPFxTUdBXZHah1207BrQ==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZlVrV1JZbS83Q0p2bHky
        cFc5eS9zNHdQU2FqRE5xRXZCOUxjUFNPR3hJClQ0VlRrYWN0U0RWbHFCbFhidkF2
        cFYwbER6VW16T1FRRkVsVzg2dW5CU2MKLS0tIHpjU0p6T2Fwc05kMnRhZTZtR3Va
        VlFvSzRyTkFGWlVvZ3VpQXVlUlpacncKfOdvIZ1w6M4PtJywpbpXAqBFye3HUpnt
        N7hWFCHb6aa2qfh/opz3IjBEwlSjfjKA1fyKR+ltdAS7bwtGTgMZRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-30T14:02:52Z"
  mac: ENC[AES256_GCM,data:t5v2m/N5764u8q5VgbaDSpkus1YIVo1+tuS0HjD0NJFuj+YKzg/N3S+cllzdRmdjb46YOi51R+Mxu7AxGoTUIRhoRMMcoKtDdnt71CKqax23slg2iGFJESbcu8Nf6MO9pmItMWtVVUtmkpISurAFIjscFHgm8J9RcYD3npa9Nh0=,iv:My8V6lCesjfIuaiUsIK8YHDGtxKyKfV1IHYTZNgGBzc=,tag:a2DnyohU2FcVwoeN0pfUYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
