apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr
        envFrom:
        - configMapRef:
            name: sonarr-conf
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: config
          mountPath: /config
        - name: tv
          mountPath: /tv
        - name: downloads
          mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-data-pvc
        - name: tv
          hostPath:
            path: /mnt/ssd1/library/tv
            type: Directory
        - name: downloads
          hostPath:
            path: /mnt/ssd1/torrents/downloads
            type: Directory
