apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarr

commonLabels:
  servarr.app: sonarr

configMapGenerator:
- name: sonarr-conf
  literals:
  - PUID=1000
  - PGID=1000
  - TZ=Europe/Oslo

images:
- name: lscr.io/linuxserver/sonarr
  newTag: 4.0.8

resources:
- ./deployment.yml
- ./ingress.yml
- ./namespace.yml
- ./pvc.yml
- ./service.yml
