apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: sonarr
  namespace: servarr
spec:
  image: lscr.io/linuxserver/sonarr
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: sonarr
  namespace: servarr
spec:
  imageRepositoryRef:
    name: sonarr
  policy:
    semver:
      range: ~4
