apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  template:
    spec:
      containers: 
      - name: pihole
        image: pihole/pihole
        # Uncomment if using as DHCP
        # securityContext:
        #   capabilities:
        #     add: [ "NET_ADMIN" ]
        envFrom:
        - secretRef:
            name: pihole-secret
        ports:
        - name: dns-tcp
          protocol: TCP
          containerPort: 53
        - name: dns-udp
          protocol: UDP
          containerPort: 53
        # - name: dhcp
        #   protocol: UDP
        #   containerPort: 67
        - name: web-ui
          protocol: TCP
          containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /etc/pihole
        - name: dns
          mountPath: /etc/dnsmasq.d
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pihole-data-pvc
      - name: dns
        persistentVolumeClaim:
          claimName: pihole-dns-pvc
