apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pocket-id-operator
spec:
  interval: 5m
  url: oci://ghcr.io/aclerici38/charts/pocket-id-operator
  ref:
    semver: ~0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/aclerici38/pocket-id-operator/"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id-operator
spec:
  releaseName: pocket-id-operator
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
  driftDetection:
    mode: enabled
  install:
    strategy:
      name: RetryOnFailure
  upgrade:
    strategy:
      name: RetryOnFailure
  values:
    instance:
      enabled: false
