apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: servarr
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      initContainers:
      - name: gluetun
        image: qmcgaw/gluetun
        restartPolicy: Always
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
        envFrom:
        - secretRef:
            name: gluetun-secrets
        volumeMounts:
        - name: gluetun-data
          mountPath: /gluetun
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: Europe/Oslo
        - name: WEBUI_PORT
          value: '8080'
        - name: TORRENTING_PORT
          value: '6881'
        - name: DOCKER_MODS
          value: ghcr.io/vuetorrent/vuetorrent-lsio-mod
        volumeMounts:
        - name: qbittorrent-data
          mountPath: /config
        - name: servarr
          subPath: torrents
          mountPath: /data/torrents
        ports:
        - name: webui
          containerPort: 8080
        - name: torrenting
          containerPort: 6881
      volumes:
      - name: qbittorrent-data
        persistentVolumeClaim:
          claimName: qbittorrent-data-pvc
      - name: gluetun-data
        persistentVolumeClaim:
          claimName: gluetun-data-pvc
      - name: servarr
        persistentVolumeClaim:
          claimName: servarr
