apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data-pvc
  namespace: servarr
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads-pvc
  namespace: qbittorrent
spec:
  storageClassName: longhorn
  volumeName: longhorn-media
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-data-pvc
  namespace: qbittorrent
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
