apiVersion: v1
data:
    DNS_ADDRESS: ENC[AES256_GCM,data:TiRmBzi9FxkW9s+p,iv:qX2x7QVhoQ7nDdvXyiHl+TnziA0Z7J1evUpEjB4/uoE=,tag:5bLIwLo1r0m2KnwEHSRC/A==,type:str]
    DOT: ENC[AES256_GCM,data:6njLfg==,iv:tAcLM1VjYOVPqwrVoxaajZRYdOLsixOZHeNosKB/fDA=,tag:K2MeiofCvHY+QBl+ouZKdQ==,type:str]
    PGID: ENC[AES256_GCM,data:1lsUNrH+ESI=,iv:TxSVtPdwruu3SyoW5sAMu3bF37Me2mPPCAloQ/M3WZ8=,tag:SmbIAdsAztSd864PSJn/Fw==,type:str]
    PUID: ENC[AES256_GCM,data:Hhbi7cqAd6Y=,iv:P/vFfQrD4HN8cGssY/uZN+/rGUjVTdUKNDdg8auVjOY=,tag:juqpeL2dIYzcYXns/cRNyQ==,type:str]
    TZ: ENC[AES256_GCM,data:GtHTJH45H2tEgIZ9eSJoBjSIktk=,iv:XOMq/UssVfFARst/jq2mjl7GPbVwCF8CbIqsj3yF0Lg=,tag:5wTz2iTyM2y6I6hmnIqC5g==,type:str]
    VPN_PORT_FORWARDING: ENC[AES256_GCM,data:FX5X5FzAucs=,iv:Q0ACoUrR3lVFOOHciS9CqkBLH/AdFyotORkXXeEccEI=,tag:ygsqmiYpyAUo62ccVpjN1w==,type:str]
    VPN_PORT_FORWARDING_PROVIDER: ENC[AES256_GCM,data:ThjH100fqlVH8OEj7R9Slw==,iv:gi9Wu4noyyUmkhtMT8DlKTcqjsBxoqCOX6uwn+PvmnA=,tag:MZHSzBZ1cZKgvPdBSYeE3g==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:CWosvAc0igAloKb2,iv:nADRLZJqVzQEJL4WfFaVsjirqzaQ7QJdad+XZS1PYL8=,tag:p+OjLQvvZuRP07EDSwd2QQ==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:uAIGvh5vS5o9iplQ+6H9pw==,iv:Yok6AWA6hloLxoYVvJyl3nNXhVeUXKpkbQoNvqDgxk8=,tag:xWb0RXkY623H+b9lFyzomA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:9hWmTeuRyluIkSPckUy1Y76LUEQ=,iv:EEdL9Yvjd6DnDaq+NrBpf4jK1UrwqLl29LeRuK3aGM8=,tag:8xb3pXLRPVbQGJqEkIO2TA==,type:str]
    WIREGUARD_ENDPOINT_IP: ENC[AES256_GCM,data:QIBYowMTDrGOOTB94l1+MU4hp+o=,iv:iHRuyXflM26TSaPdpwltA91hF6T1PW2y9ADSkJLAFn4=,tag:fBCqdofwFVWRJa7FqdudUA==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:UGUoy9tAFQexLkL6,iv:d+Nyx9Vv9FPTuhk4c5/F3CnlRABRaycjTWlggGjGmTs=,tag:mYJPc8F1qYZiCjIdSvSvkA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:KUXTZQvOhPSf7/SYf2ut/O9ur7eGe6rIYi8NCtANuwYWLoKazjPVomm6S4DLqEY8UK3PKrz4yV632MvHMsUnFA==,iv:XAWWQxLjYybgujIbCS1l+W9ZlCa4qiYgTXmgpLEL1dk=,tag:qhYCpQKW5cMzVgOnzyfaDg==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:GLUixPnRZEHiJk7g4xAOJDvyoNRNviiJtxDiRyOnJv4iIOsyrobfXer9MxHrGdnedwRuf+OLYmv6xMyQ8QFMgw==,iv:ydZpqBxI7TOg7LgBHDNmOyAcKY1wykSp/zCBAdKdzp4=,tag:/sYEgMB1xojbd0Y71EE8cg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gluetun-secrets
    namespace: servarr
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-31T01:24:31Z"
    mac: ENC[AES256_GCM,data:km/gs8jftS3pY3ghfES1CG8LZG6QpoOsWOMmNvCvk/7dh7KNGoL5WMQd1Rg5PxLpTmm6+QiOL0V/LynrhXGhyBzAf1ePnAxyTHnoOAIt+TsJVvZm3VOZuSEaHJBLQOK1k+G1eI41pAOdvEqMfVbrpZD67cJjNsigkkRSNW04oHM=,iv:xbzrTNLy6RkogbKxppNy05+mClhxud/jrApX+Y3V99w=,tag:x/aJTu2cB5RDiW+/HfwXCg==,type:str]
    pgp:
        - created_at: "2024-08-31T01:24:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA07vNzTbDfvLAQ/9Fw5mWOkYrj8nt6amf3jrawWpinfRZ9zaVnPqPZUnDPyX
            ODPZL74tXokAHQxM+KE3q1Q5jkRP1jR7Ymnri/uyvtNbD9LE82hEiqEL2toxOU0l
            jDkTOLMmMxmQuFYNKUcu8ZbT2n+Dbx0kwahzwMabUeBKkSAmk9O7t2wRdyu8w0dK
            oHS3zjwiewK0xSj34quF5b21W6s5HREXgVXGDIl4Mq0BjsQPG+1/LCw7eLTY/6ww
            vsdh/Ctxfx2sLlxctzBE4OAjZqVL9O8cBovB2wUbaNvCacrS4/caofVycspWsp3C
            Y7hWPTc24Sm1X8SnDdbClbSHqCMFBLdmg769to9SzhA9qO0IxZZnoJUJ8eitly1q
            ja8b8ZFIbLkRfjU6eDOMQisgrqqKPP7hRtnCKv/bs6GIbW6nLLO/yDE7ZxMVoyGA
            3L9LnPHZ2EJVCDSrDDOIUeKSE1OrSVaJDDIT7hsbjFnSQ9uHmH+0AwJE9UZ/PuIf
            5Ky4Ksh/j8/alFyXquXCWNJ0TQJT1f7kuXAQq3o01vuWa7UdHIF26vwlGOVmmotD
            tmPp+wFhulqvyY9AKrSyFt9Ixjf4kGO4KEv09vHiMZwUxfsdWJoD/haygGpyTMbW
            Zn1V/mEAGgsn6T85i6aKcG0StUN5qjp4BuRoICb4yuFMz60GLH0Du8fHLoS5PaLU
            aAEJAhBAInOnppx2wf4gDI6nNwle9pR5PhHS1xfv8dIvp1eHG9BLzAYSuKACv6b9
            jqfInArx/8TS+8udSRKfWZlWQ74qGmpDmdO40djL5zSrdg7ZGA9pwvgHpfgYJEh4
            ZJVHXUoRRIvg
            =uBJi
            -----END PGP MESSAGE-----
          fp: BEEF34650B1A582788B74532EB69A1EBC3136E00
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
