apiVersion: v1
data:
    PGID: ENC[AES256_GCM,data:W32or3aNefA=,iv:fqmRy7behXAMSmENgqDLKzGbHop8zvqbQ1q+4RENOs4=,tag:XPAJsjQIYPYbg35Qo166/Q==,type:str]
    PUID: ENC[AES256_GCM,data:FGMZhhbqfpk=,iv:MQ8FYaGbNO35qYuX+1U4nk2citycVwAJEexgzqO2y0k=,tag:srg8aC+IqBYrfqZFHwvjlg==,type:str]
    TZ: ENC[AES256_GCM,data:HYlOKLPq34qoZsYhhq48Opf1T+U=,iv:6sEgwamzi8uOwX4sZ8hSIW1qGTXu8YhJQFaBJHM52+Q=,tag:1gOTWkYMTn4n6JZiyv2FRA==,type:str]
    VPN_DNS_ADDRESS: ENC[AES256_GCM,data:v5g81IaOEAdEVOYGhKO83w==,iv:4jhjC8JLvnEF+705I+6kOGb2IDgkdinXK2mRXW8hkUU=,tag:BeeKpUYv0zEpGIlH6/fk1A==,type:str]
    VPN_ENDPOINT_IP: ENC[AES256_GCM,data:gD+rHWw4OumB551XzqfPKOpVAJo=,iv:heFEwo4XFMeMVX3HjwoHiYb/ghnsTBwphVLFiHkNNU4=,tag:sx5lH1Su2p1sXQrIS/KdSA==,type:str]
    VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:h59M8fUUO6/L6a7k,iv:8qEMayNtwYhFAvTiJLg6xQsv5QpGTfp9axfA2fOQLjg=,tag:RoXQ44KdPJiKDggarnxL1Q==,type:str]
    VPN_PORT_FORWARDING: ENC[AES256_GCM,data:BsNRirDy3to=,iv:xZDp8AAjIkivnWfdrYk7l6e3KbggNWW4ARjxmdOvWEE=,tag:s281NtUTOwNXwiC15igEPw==,type:str]
    VPN_PORT_FORWARDING_PROVIDER: ENC[AES256_GCM,data:Qn7itCaL8WI3DgK4psn8MA==,iv:W2V+oeSTD8++4zKhtj6NLD7JpJ994g4nEJ9XsKgvO2E=,tag:wflwnUNkaFLkmsYU/Yfm8w==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:1NGz/N7LdgmfskPU,iv:TanawZcLh3tHYK7/y8QjpTcUnIIvgBTdXHlPAgnagGk=,tag:fCSADbfRU2B8uU23N9MFKw==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:IDClDunvWXc82RSyZzBKPg==,iv:z+8iOAZBXQLNYEaIUQeOe7aJokqEliFzEunoWOMTl8Q=,tag:zsxuQfu8vSqxEhnnCD/Vqw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:MTETxeqYCBX/wlkDoJXmlAX+MIM=,iv:MT6iWkMZUoZVwikscBF1Hwhj7Nh53DXE8WJ1V8M0j8Q=,tag:mlXBW7JVsFIZNPkehGb8Lg==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:BiOggBgOV+wv15ykcE6VhxAbDNLE930bo6JYw65xZU6LuxL/XJ2jvd0XuY5A59Jgud41EllCW/eLNWP6XPPEUw==,iv:GMX+nblojV4jBBxm5mYXCNXh6sIMI5Nps1OEOucmiV0=,tag:QcKawFXRhDcIvH031qQ+Dw==,type:str]
    WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:PIBMNAy1M68M4oCI2JpAF+yVPOGyfam3IrLvNlJuorHBvnUib1fcOH4lK8ltKDqRS4Ec17XcNUv8XsNBUG8f3g==,iv:HSrY4majz6auOkn6HKRx+IyMaMhKgbjs3GieOahDFtk=,tag:zul2DJQA+csKYq8WpIet0A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gluetun-secrets
    namespace: servarr
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-27T22:11:51Z"
    mac: ENC[AES256_GCM,data:UHSoQgbrMngNPjG3fzzDXIwc+vgzUBC7yhG34ptd9uXLrmYmAxF0aw3sghyeI/e3foYUiCt8vrh7gnozaEaqDBsac0zS3WYrvyiFtj5oDgyR4VeBau0u+G2C07Q1HKO/EeisvjljogjLDl2V7g5u7rzk0wv8J3mE7QmKRSZ7ul4=,iv:NfmMpfbATLBNQJNBbFtEo2tNndnCoa2LnCXVyLob0Ek=,tag:pFURpyQboSarKjFrI4EzIg==,type:str]
    pgp:
        - created_at: "2024-08-27T22:11:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA07vNzTbDfvLAQ//TNSUvhCPBaCK1x6khe/a+dZApKFdUzpCLHWcyzRvWtQr
            ZFEGITB3HIfrWvzJP8UuWLaWnHjuJ8keLNjcN6ksR4l4sgrB8ePO/lgP0ZWc25X6
            U6AZbdTxZqUMtI8A955b1GVaLBgObpWC804Cm2VCtn1FLgo3KgQN200lpqBHF2Gw
            qQdNJwbthNhlsMPVMGbJSy5BxbjUVwgoxOWXcvVL8TJGB0LIDV9JB5VSpYgMqbqM
            s0rhuz10zE0gzW3iruIKiE8CtFd6a2KlnJsVQEkolK+dyRi7UWAgKQjXkscDMEun
            mU1B49f2JwgIlJfJI/AWhWtcJTu5SPmJb+1rrJb4Iu7sISZKggIBSH/VHB5ElDqW
            2G1iH8wg1qQjiu9BO9VhupWJGGiDrJCf2hz1QjVKvalyHYV0xffQP7jBbcXoTr+k
            4nN4o5c9SuQVbPEaWCXCR9Zrte5y14vaBXNn9aejKJU/YNsr3oy+SzNI4Q+GHPF3
            +eEiiSUGDr/HlWCIeC01nd/Spm+ftComphyO1TwU1sRxqYmazv0CZBZFFVMBTo6C
            DqYr0m6ov5xkkNf+XBzGrwBEC5sZaPiV0gGrLHXAHwVRMx9abDhDcnZkmT408RE+
            xKlelwW5HuRWMJ7Hf36E4cBwOmGxVyoaqf9YJ6F5rVgB4pj6AjXT5JWvh8dGxaXU
            ZgEJAhCG0MAN4TJmi3S6L0XWHQHkndhkGRKxKkzHziird2f8h1xWQzPvPsaEmOto
            nZA1W7KALdSZdRnLh2l3M5gwJO76Y5kRkH9C0u3actTJ0nti4NBopwsGPHyAu5cH
            zvg9DrBEhQ==
            =h8ND
            -----END PGP MESSAGE-----
          fp: BEEF34650B1A582788B74532EB69A1EBC3136E00
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
