apiVersion: v1
data:
    SUBDOMAINS: ENC[AES256_GCM,data:T93/LmVHNc4=,iv:XCxKJMeT0ueeQ3hltRDG2oU2rM8vfip15Chijpef+co=,tag:3fohLW0/7ApLoIZLlyFRYA==,type:str]
    TOKEN: ENC[AES256_GCM,data:mii5HYXoRSk63Va3Tdz0NIWg1BtTLuNogtWBj6dCipPETznmJtHgQdsmFuXzxrwF,iv:IZ47MuRFiwxH/Fx3OKKJiR/rz9uTfMz1Hc66ZSOIw70=,tag:MJdiyws8q9QyD3fkcZQMLA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: duckdns-secrets
    namespace: wireguard
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-21T21:54:27Z"
    mac: ENC[AES256_GCM,data:yVUKZeT+GLGawdP8m1n3Bj/vCJjn/W0LLu1KpzQoN05eBvLKx2gFadK0/OOJ06ZBN9dI7SrNvtGvOQ4wm6vvPMTRgKQos5cyKUXAlRi0s6n+WC0ffagc/knMW5MBuXb2dJssySwG8zmRJKe4QRBo2bgP63R3R48CDGJsp4FqeSw=,iv:Ihsk3F0qIAypTvw+FHiIquGkZeMCUjDni/cfSOgWdj4=,tag:cy4LYhH5kk/JrPV2kQpDeg==,type:str]
    pgp:
        - created_at: "2024-08-21T21:54:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA07vNzTbDfvLAQ//QNOV4hSWttoSv3L/Mz8Md9f7H6usoyoicUKK7Uf6wME5
            jpgm/JbxrwrUcnmkHB/Isv35shpVlzIHxKN6/FhWNcbef2EugZAYBX93KsDvuuqc
            fXd//stUWOZWCaRmsKwDj5eFU2KRvjd/YmCCFjVu2Pcjt6uIHVqWq7mXgNNSSfdr
            91/c+5DeWEvRcjg9fnT3VeYzxGPrcIzgbRzVYj2IxrbFp+6nd+qYw1s/8C2zXzce
            yeDJXxl3tWMeXBLQ8bOnVqT7Y2wTRchjORHD/cPKUBX1qU4zgVa5yGC51Rlvi/x3
            xL+8EteH0AMNXHcQAczRKnc2+b3fxWONuMIQYM6nM/qbmZuPfG3/vCOVp09Y/Epe
            s1UOhnvx3O2AzDcfVRTs91XuCRSsn+ZFDl7dGpfXTdSAaIjBGhVSkBidt5tDCgGn
            XlFKX9DJaABJ5i3Becc/c+/yecyn54pHKJIDfCxgRLtct+0Xz5y9MqZRjZDn1bHu
            vvOkLAIb5V6UpXQ38K7m/xwHnJc1jC6o5Ly0owugAo7VsLTkki5RP4HahroBGiJv
            8Ai5W+TVHIaHR45d6XX/2zABosNzWr70L337wTvySqRcpUoPqOf+HjqWXmZ1GNhZ
            3OMGQ0ORgKKEOUp+IVZNHVcHVqNZMCyT8lkwCQSS9rdc+iPYKjUU9saoxkklS4LU
            ZgEJAhAy5M+yMSxtgO8yjF+doCfyoco3SIiCyC6cKwests40R10G63HD58f+dZxb
            cin5nDwabMOfBsdgcktjkhbDV+VYs+mr7OPBf9sEXAWdhglrd5T9uh3nYhLn9Vm3
            RmFVmAW3Hw==
            =u63M
            -----END PGP MESSAGE-----
          fp: BEEF34650B1A582788B74532EB69A1EBC3136E00
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
