apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv
  namespace: servarr
spec:
  storageClassName: longhorn
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: servarr
spec:
  storageClassName: longhorn
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
