apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: servarr
  namespace: servarr
spec:
  storageClassName: longhorn
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
