apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-http
spec:
  acme:
    email: letsencrypt.chaps970@passmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-http-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
