apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
stringData:
  address: ENC[AES256_GCM,data:Z2vTSLjiZ61qCa43+fZD0MchlevXfw8aFakbXiSxvtDDmxlfLBA4tteyEmym37w3YqbcA4T0TTaiEO6o7FmzgYglS3p+8D3bOHPC6I9OEw7kjfwvgeD0v1Rj4bc5Dlsuj0qLo7qDwdw3aU9Gd3hBus0+juuglTLdJaxA0aJPQao=,iv:19suhTFtAOSgIN1GbB3+xA3rCx3050qdYM5Bo+bo9b4=,tag:loOJtgr6iSbUrIJd+PW0vQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17dhlnu9e4p3lmuacnaecg0vsrtj35ant2qvzwv97vy7sq0yhcq8szcttv6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXeWcvVjlDQkIvV3Bkb3o2
        UnJDd1l0ZjhmUTFIRE5mMXRyM1dibXliZDBrCitxRDYrU3Bvdy93amlSdWdyZGNF
        cE4yVGVyeEpaMllxWE5IdmF6WEoxb0UKLS0tIEpLdmFLZUdTS1FJU0tMUWlFdEZa
        b052NGFTMmxzTHZsTkhhOHBmTlNMSTgKFxzgPrLF0FA0mKQxeOybz8YiqEkKDorf
        s6TW4F6QAvSj6KyWnNdbjg8dcJcMKTQjDaZ6kfZ8zEoy9eiR8uD5UQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-01T17:57:28Z"
  mac: ENC[AES256_GCM,data:LxwCZwYEf0AlHjeNL8l23eVQiTVGVgNi+GgrpmMMyN/fNbaNq9oJgEZLsz/0nKhMjo8ZP8syvLR8H+uhfO+vqKjywfObbhT9cbuwwS0w6w5RW6iZzUVVW7C/Bb0VPdALElaf6Ms8pssWlUcEClAnzNjixhN0cJCo90w4hw2Iqk8=,iv:CVwBs+N8vadBd6RSGycCfqTbGfC2As/ML2YtYGt0TqQ=,tag:SYDEVi/uyPBlgWEdilaIgQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
