apiVersion: apps/v1
kind: Deployment
metadata:
  name: failsafe
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: failsafe
        image: ssouthcity/failsafe-discord-bot:v0.1.7 # {"$imagepolicy": "failsafe:failsafe-discord-bot"}
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: failsafe
      restartPolicy: Always
