apiVersion: v1
kind: Secret
metadata:
  name: failsafe
type: Opaque
data:
  DISCORD_TOKEN: ENC[AES256_GCM,data:1yBFB4TdZX0i24kfIOUaoFBuJy2ED5vgzw70SKc4KINg1XT1BAFb0d9O5U+FjxKPUdcSzE/tUUxSJEnzD3kwrV7F3dxcqA==,iv:IgBm4Cn9KMvrZ7+eabKVsVETPv3W5H6nABq5VWjdkCA=,tag:oFD+1cGkKRUApl6Liuazrw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17dhlnu9e4p3lmuacnaecg0vsrtj35ant2qvzwv97vy7sq0yhcq8szcttv6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcGxTZUI1NmFLbkRWdTZF
        K25Ickd3UXRLem82RVF0amVJaTh4SVhiS213ClJ3dmxZMVdpVmNBYWlGQ1duL0Ft
        OWR1Y0Z3Y3J4Qm1WSktHcHUrT2ZwWm8KLS0tIEpZMkFJVm12aGFqUkJQU3Q0a3ZJ
        R2F2N2FZcnFyc2FiM0cwWldqM1FkV3cKth2wbHitoHMhdShFvFDl4Ivb8p5cV8K+
        Zxwb14yH62aosDo5ySOyCXImzE2oDXWDWcXNubbFLxJV5+KoGvUIMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-01T17:09:15Z"
  mac: ENC[AES256_GCM,data:nhUPWU5347+mR0yJbzR5LQmAqtaC5ww7iGQK69Z5xBOcVwIhPWeeSvq/uRXmNroFgs6NrVCGn5bCGKkc0bGNlVRGH85RoiyRO7IUH8EPFPs+O/aNWqTAimdh486yeD/ZUauh6jwcAIfMVBfb30UPBZ2/7rzjQGMKKYy5GGYzT+s=,iv:4gwpR110EEWkOySlMcgtK7Wmj0/HRTq32/nSH/c5ZlE=,tag:xCTuCvZY20ioNlit4gh76w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
