apiVersion: v1
kind: Secret
metadata:
  name: failsafe
type: Opaque
data:
  DISCORD_TOKEN: ENC[AES256_GCM,data:Q5w0LB6kK2QI66vxoLngZKNoNdd9BzG0Le8mBZZtcP6ejfErP8O/nczJzgJ1md0e5l+a3ZDn8VXErBFD+tKNkm1JfbxPCZa7hi1r1yICW0uKE084RnX3sgPggEeXKfvD,iv:d5f8pLG6LON+AddgBpJg+m1/w0U6C5+AW6iYwbCeziM=,tag:ch8pxSkvc3J5/MM+4Z17nw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17dhlnu9e4p3lmuacnaecg0vsrtj35ant2qvzwv97vy7sq0yhcq8szcttv6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MzFyOHJ6ZzgyMVJlam5s
        emRPNHp5WWJLblFlNGl3K2JBVzBTR1hhTHp3CllsOUt4UmR2bTZoNHZnRHZQTG4y
        TjcwTGgrL3VzWEFhUEppZnI5RmxYdmsKLS0tIGRjRnhnUXc5QXBJYk1qRkViQ2tx
        UUJ5TS9DLzVTTktoT1RmOW5LeHcwb2sKLEuplgplhRW3Y4IHaUlalnBHelCQKjfP
        CB1keQTyM3pUvVau4sAzd3Ym3RQTnVE61SBd33NChqvrLjqfBDfvgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-01T15:23:32Z"
  mac: ENC[AES256_GCM,data:VuLH+imp8y39kca1g52XcfvusDozVk7OTQSYFFY+NECqMTMR2cmviRLdvrbUwNwL5cLvioIJ8+J//zn/YUwkEg+YNIt+u3T7C/4+sBrpGKVzid7VCozuz9tQunoVWDKE/IWBkvylRH3l6hfUPPclwhl3c0VDNKmmJhaH9lhM+Nc=,iv:M5byNJny2LK7xBjn031mATo6GOQ0yfu59WXrII1YWzM=,tag:wWJ4vCCoNwWvwRBCJCthbA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
