apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
stringData:
  address: ENC[AES256_GCM,data:lmAOacWpb78eMW00b3aEqmdPNJp5eSZ4PPEtL8yMd7loH4L0me2SDDtoSRpFLd4GgspXP71xSh8Q2TN55sRrF/lL838cJ1vlHrKesSfhfS0YHLmt4YLjypjCPeNI1+7iVJQVOTO5d4i4VOFaXEV1FDSA4PD/9as1qA==,iv:eQgaNxD0YPFV6nEN7dSfjXpfFwORjXUIgqAke2BhAm8=,tag:YfJKeFwZxu4lDA6SiM/Kcg==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRHFpM016MGdNcjNEbFRL
        SFhZN05MWWhUUlVtY09La3lNampkUFUwbUhNClVvUzBqQmZES21EOG5CNTlDWmZF
        Sk5ocENnMkJzTjQxMFJOUEd4VDQxOFEKLS0tIFp3eDNRV2N1cmNmd2s0dDIvV2sz
        MUNLUGU5bUJQbU9iNFVHRGpObysraWcKcGZzfqKOQZ7ZFlSw/75nx1m9CiYO+Edj
        WuCaggndjogJn9yvA2z1Rdg/FH9wCPcWKqVlRVUgKAId6IyQSOXmMg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T13:45:12Z"
  mac: ENC[AES256_GCM,data:7LmNIgByB2BPwtP8rTUB/4jyPuDIT0Dwqvz2TWjN6UNPPLpJwnbpo9xEoGSzWe3H1R6Z72yuW4MFzYekLOnvqABfdRLr1SGOrJ4tU5ElvHItRPLR23aViXw9Ers1xACqLMn0HEFyLdYI1laOcHFbbwOAyC8rt5/szowqkC4NBQU=,iv:KIFB4OK7ypXrYUjj2QMO1aUQBKC8lXtl+GnmiRXSuas=,tag:I6nvQ7AoWYDQXJt+R1euyA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
