apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
stringData:
  address: ENC[AES256_GCM,data:G1IgjlQgryxggOpkdZ/UDFvBbVdelIm7ZmTpSU/d1tHYwDDpJcS6OR49WwOluHAO2VtCIKnrDpfhK5whcmaWrxYjTDzloh9MprVIhveCwb8uDFOa3wpd5Vn0UAUt2q5pfs5LW+dayiEKS2+i5erocd/DVmYWDHExzw==,iv:LBAaTVDu4Ye/DGRReiEJZpkJUAvDIfRTeiBUluPCj7E=,tag:1UzI3M88cGFPrSak0fBKsg==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMC9PUVplZmFWNWJjN2Rm
        WXpKSGFYRi9aQmlOM01CRWJjMzdVUXR1VUhBCnFZMVRpOUJtcVhPdHg5cE02QWlX
        Z3REaGdNNWIwZUE2dlJjbDM3Vm9PWVkKLS0tIFp6dWNZSHVaSzNtRGtsS2NMUlE5
        Vy9DaVFIR2NodXN3QzBsU3oydUVYZ28KXxEJeLLcw++w/dcI2Q5FsF3G/KCD1aOy
        ak6xTSMHaYcnn462TI8Oz9KxDRZI6Y81b+zdU0So5arFrs6qu3hk/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-16T22:09:34Z"
  mac: ENC[AES256_GCM,data:tkMN6fYLKvzOy/HFXENs5PwthCWq9osIL64+FwyfgsigzeYoYOrsw7aNAfrzbqo1P8MrtnJedEFhr/sfrnP++pSetSQ6TpGODPsGyueIDOmZ8dec0jky9aXK4fnqBqmTaZOmn5IsrZV3oRwYW6WHJ86jEFKidRPFORKjCiYMmgw=,iv:lyZHrjhv4/e4vQWvPibdKJMdJxc3935AJzmhxAiR+eg=,tag:3jJfI3voIZSzEuNxKrEcEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
