apiVersion: v1
kind: Secret
metadata:
  name: vercel-credentials
type: Opaque
data:
  token: ENC[AES256_GCM,data:3anWkUYuzRU0LQ2wreQOS0/9hsi1kGtHrWYFLISzPwPFjUn4,iv:xsOmOOgkUE1Zxpgdzm7mus6tOAEEq2WatUj0uQzwVkE=,tag:0XFgQBdrPSARbixKZzys9w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17dhlnu9e4p3lmuacnaecg0vsrtj35ant2qvzwv97vy7sq0yhcq8szcttv6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhY0hJbXRZQS9HbDNiZmNl
        c2luOW1yd0JhY0ZMYVhHcVhhTVhva0hXQ1ZNCkpYMVBob0dHclBzVlBGWlF5ZzJC
        enV1Y01QKzNocTB5TlR0SGp4SHczamcKLS0tIHNET2Eyd2FxWkdrczd5dlUxVC95
        Ynp4MXcwZDY4aFdQSDBTMmJLMDdvUkkK3wRe+2Zth7XF0jlb1hNBmKFppEolMAA6
        Mt2rT8L2I6YQGys2ghFdwkNevBPSk6OHOTmjTtKkldjnKZyTtf6PWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-27T22:21:28Z"
  mac: ENC[AES256_GCM,data:mPam2cKUZtf73OlVUqyj8PJ/sQ3aYHm+iAxE4aFUW/zL+731vbfhLSAt7QVm1P+LQV3+u3pmyjPXGQWt5IUoQuy+mAgH68FC041aeIqz7jqk7B30EBPPV/rA++UnrhQ2PVUQlvNiyy6DkDM8JvysK+qtIXx4jRBYm6/0PfBPTXs=,iv:LEzjAzgThesryut8kUes5k+g0ebPYe44ShItxPaip1A=,tag:4fX10DwjISauNUPMG2a4LQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
