apiVersion: v1
kind: Secret
metadata:
  name: vercel-credentials
type: Opaque
data:
  token: ENC[AES256_GCM,data:aiYELf1lG32QKW2ozNjrluELC1vA8xRK,iv:nP4n6XMoXW71T5nYI7xzg6vbpPpsbXyGHXAwuBNUQt4=,tag:nkP0l4qndS8Xz/ZL9Appvw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17dhlnu9e4p3lmuacnaecg0vsrtj35ant2qvzwv97vy7sq0yhcq8szcttv6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QTAyUzg1UmFsMUdHNWxR
        ejkvYThPSWhMTDZXVmNrUFdPOVd0dkNnU2dZClAyaDdVRVBVbmFmTmprMkcya2Y4
        SWFiT3hoc2NXVXhmM3V0RlVVTzRlMHMKLS0tIHN0WlVQdVlmVWd3STFYNllaQkZ1
        YmFMaVREQ1pLU2pVTTR3S1R0QTFVYTgKOaKwZ0oQAuc9QuJMLM/RcqcR+aBgbXD4
        EzNcsv1QST3/nkMt96ynnPJH52zVXXthIc/8+tVR3sFbsUlaRECAAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-27T20:33:33Z"
  mac: ENC[AES256_GCM,data:28i+X5nAprSRDu2TEn8Kx1Liw1WJ4JhRKIhgAWMqczogSVpY0KV9NqhX9to7K5XPdfHd2UKJ0WU2TSV90CcBuZhtPBvLBaOI6UB9OtTv14hGRJ7OzFDFVZycLDehvo0zRHFu9ZFsOJQp6N199tGoCCyJO22J4xTZODVEItZYbVk=,iv:H1MFQMuBdE67jbj9UekL8KzgtfXQOYhE3BZhWgMHJFw=,tag:Y6JRdAtTD2nvvNI3vAEBEw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
