apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:d+ErxJHI+g9Z7/3FVCN2dJHLjasusOv0XtPo2cT/5fUjHj3psUVYHA==,iv:eMtsumc/vQIAj3jVDarIxFlo1dpRaNyiYflaIqTwpqQ=,tag:N492xHHHm/wnn0G0d9JEoA==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcWZzdWs3K1BzSTNlY2pH
        bGlGTjJsQmVUdG5qbGx5bmpnOU1HbkdVZjFBCkNZeGsrY2d4MGlaeExMQ2MvZzlo
        T25za2p1dUlGcDFjYzB1bno2UDVRT0UKLS0tIGlzejhGYXNuazlOMjBHYnZNbGp4
        RG5kZjR5YXFtaU0xbHAxUTRZbHBwejAKMQduqVbxnGRmCQlh64KubBL3ulGo6cI6
        kPNcGmYAUxBTEzAmYDQvodRy6/ZoIotYm7gwYAn10xfvK5FxAh2pbQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-27T00:06:02Z"
  mac: ENC[AES256_GCM,data:q4cGGqKw3gej+Ily6GB3zgFexfJEYWk2rgwwRdeII4XgD/f7RKunBmQDtjJCuiFjJRXygOCshRdEesfvbkl/fM0CmMOV+MD20KIGeIsx7HhN965bE7DR2HSyRNtxvcFLk+BVM7jkgUrTRBaA2fjyjsv+AfEjpuEblVNAtP9ezcY=,iv:Ieb3znsenlcokNTYaoSrJf2NOG4rOZEmQQHIU528BZk=,tag:a2YxK5MYnXCkqA3YumrqMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
