apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: kgateway-system
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:+gltjfaupiG+Uau+20aiTMLsMR6h794msmavv2i4L+1E0MUdy2hluw==,iv:blNJBbEXKFILQ2r/w4PTlgDHWW4c3IRrifrbY4RYLBM=,tag:EFJhtIifOdZHNhyn76ItNQ==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2T0wyTFFBeHQwVU84ZHRo
        dWxQTHNiSmtNT3U2SU9xNmh0dEgwL0UxOVQwClU2MW5Oa0FMcy9UeWVmaitiRkhx
        ZTZVS2k1VGdHdWI4YzI5WjNuYyttU2MKLS0tIDNMNU0vem9FNDFIbHpVNWJ5M0RU
        TFFQZTFrT1BtZkx6cFhTQndubzdrQXMKb/IdJjB/8Jvwn1Q4F8G+HFibDoUiIRdj
        CubAxc46QAiH6+DqhuXdD3E/P9SG/CPhU//4oV2dQPw1me+Rb273mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T10:44:36Z"
  mac: ENC[AES256_GCM,data:WbyGZpNl/feLc6eMSnXCFAVda6QyM/dMtcdm3r5VgHikK8zZN6Dx0zmd+jTJoZtNbQtIankC8ACv4lCfqHyhmRS4xYdUdM8eyYio0i8xmK7AJIY1Kz5DbkKGSNZMm/X13Pd1xvel28Hsdl+orb4YzCDb+Z0Zy/NoYArvdVyf9n8=,iv:ho31wahyMtDOu96Ry/pghWM8/q5Hh9g0gTNQcJFkC+E=,tag:UR+OF0XX7QPBxgqMrWRRGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:FkybuJTvToiwZU/+bmZ7H3bkUUxfMYl9tt8tyPZisDvs6j9JsWA/DA==,iv:6zqz+2adtQCEcJWpkBkWE7C/A6wrNjM+2DFR/gfaB80=,tag:iBxcCMLoVlNWJqDqGvRgaA==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2T0wyTFFBeHQwVU84ZHRo
        dWxQTHNiSmtNT3U2SU9xNmh0dEgwL0UxOVQwClU2MW5Oa0FMcy9UeWVmaitiRkhx
        ZTZVS2k1VGdHdWI4YzI5WjNuYyttU2MKLS0tIDNMNU0vem9FNDFIbHpVNWJ5M0RU
        TFFQZTFrT1BtZkx6cFhTQndubzdrQXMKb/IdJjB/8Jvwn1Q4F8G+HFibDoUiIRdj
        CubAxc46QAiH6+DqhuXdD3E/P9SG/CPhU//4oV2dQPw1me+Rb273mg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T10:44:36Z"
  mac: ENC[AES256_GCM,data:WbyGZpNl/feLc6eMSnXCFAVda6QyM/dMtcdm3r5VgHikK8zZN6Dx0zmd+jTJoZtNbQtIankC8ACv4lCfqHyhmRS4xYdUdM8eyYio0i8xmK7AJIY1Kz5DbkKGSNZMm/X13Pd1xvel28Hsdl+orb4YzCDb+Z0Zy/NoYArvdVyf9n8=,iv:ho31wahyMtDOu96Ry/pghWM8/q5Hh9g0gTNQcJFkC+E=,tag:UR+OF0XX7QPBxgqMrWRRGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
