apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-encryption-key
  namespace: pocket-id-system
type: Opaque
stringData:
  encryption-key: ENC[AES256_GCM,data:R1Mv7lgYRqNXgpmLEamYwLhyga7DeIdYVnXShu4ZX80FbTPWqLCYtYdZrNg=,iv:aKLO7mkVE1SGhqwCTFYklCuSAvD7ZRLyytPWO2alfjY=,tag:c/sJhUNFGWZXVYE7JwOB5w==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWGhNYks2SUhFejBJOXNq
        d3FhZzIwY29pdmY3MTJKNldxMVIvTlRJbmcwClVWRkZXOEZGTG0xRGpXc0lpcUdy
        YTlaczVIVmhrRU1CUG9LY09LMDNDS2sKLS0tIENaemlKNWtieEdrZ2RwQzZ2QlRB
        N0R1V09URnNoR1FyUzhpRmsxYW9VZVUKdzRJytJy/aePNk7hKsV6P+KlXp7O08u7
        b4agJHW94da2J5RoP0J05vOXYxhqAnhqONh+Dl5mdfdvkJASvmWj9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T00:14:26Z"
  mac: ENC[AES256_GCM,data:nFrHdKnar/BDx/jpPJ1oSz88MF+t8GwVmrLQxMZSk4+opdNaAHjNrruxNZZmD5Aa4QLm3pAjs0ZScz+qvS9k62QcYsqJK7OIaxEtDdolwYspNBTgPm3fE5Kt/aFcG4VJeSVt8E9R+HRwtw1v4Qbt2cUAb4vFmjJu325mEwlVHtk=,iv:5AQhgZYuVKoYQU/M6+PI/15pAAaSqDW5PRsOSTT97Vc=,tag:GmTVFt+UAIlxYUnQNX+ojA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
