apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: jellyfin
  namespace: servarr
spec:
  image: lscr.io/linuxserver/jellyfin
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: jellyfin
  namespace: servarr
spec:
  imageRepositoryRef:
    name: jellyfin
  policy:
    semver:
      range: ~10
