apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

commonLabels:
  servarr.app: jellyfin

configMapGenerator:
- name: jellyfin-conf
  literals:
  - PUID=1000
  - PGID=1000
  - TZ=Europe/Oslo

images:
- name: lscr.io/linuxserver/jellyfin
  newTag: 10.9.8ubu2204-ls23

resources:
- ./deployment.yml
- ./ingress.yml
- ./namespace.yml
- ./pvc.yml
- ./service.yml
