apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prowlarr

commonLabels:
  servarr.app: prowlarr

configMapGenerator:
- name: prowlarr-conf
  literals:
  - PUID=1000
  - PGID=1000
  - TZ=Europe/Oslo
- name: flaresolverr-conf
  literals:
  - TZ=Europe/Oslo

images:
- name: lscr.io/linuxserver/prowlarr
  newTag: 1.21.2.4649-ls81

resources:
- ./deployment.yml
- ./ingress.yml
- ./namespace.yml
- ./pvc.yml
- ./service.yml
