apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-data-pvc
  namespace: prowlarr
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
