apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: prowlarr
spec:
  type: ClusterIP
  ports: 
  - name: prowlarr
    protocol: TCP
    port: 80
    targetPort: 9696

  - name: flaresolverr
    protocol: TCP
    port: 8191
    targetPort: 8191
