# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json
sonarr:
  sonarr-anime:
    base_url: http://sonarr.servarr:8989
    api_key: !env_var SONARR_API_KEY
    quality_definition:
      type: anime
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer
    media_naming:
      series: jellyfin-tvdb
      episodes:
        rename: true
    quality_profiles:
      - trash_id: 20e0fc959f1f1704bed501f23bdae76f # [Anime] Remux-1080p
        reset_unmatched_scores:
          enabled: true
    custom_format_groups:
      add:
        - trash_id: f4a0410a1df109a66d6e47dcadcce014 # [Optional] Miscellaneous
          select:
            - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
            - ef4963043b0987f8485bc9106f16db38 # DV (Disk)
            - 1bd69272e23c5e6c5b1d6c8a36fce95e # HFR
            - 7ba05c6e0e14e793538174c679126996 # MULTi
            - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
            - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
            - 06d66ab109d4d2eddb2794d21526d140 # Retags
            - 1b3994c551cbb92a2c781af061f4ab44 # Scene
            - 7470a681e6205243983c4410ee4c920f # VC-1
            - 90501962793d580d011511155c97e4e5 # VP9
            - cddfb4e32db826151d97352b8e37c648 # x264
            - c9eafd50846d299b862ca9bb6ea91950 # x265
            - 041d90b435ebd773271cea047a457a6a # x266
