apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  template:
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-data-pvc
      containers: 
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr
        envFrom:
        - configMapRef:
            name: prowlarr-conf
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: config
          mountPath: /config
