apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: prowlarr
  namespace: servarr
spec:
  image: lscr.io/linuxserver/prowlarr
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: prowlarr
  namespace: servarr
spec:
  imageRepositoryRef:
    name: prowlarr
  policy:
    semver:
      range: ~2
