apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: recyclarr
spec:
  image: ghcr.io/recyclarr/recyclarr
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: recyclarr
spec:
  imageRepositoryRef:
    name: recyclarr
  policy:
    semver:
      range: ~8
