apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr
resources:
  - deployment.yaml
  - secret.enc.yaml
configMapGenerator:
  - name: recyclarr-configs
    files:
      - ./configs/anime-remux-1080p.yml
