apiVersion: v1
kind: Secret
metadata:
  name: recyclarr
type: Opaque
stringData:
  SONARR_API_KEY: ENC[AES256_GCM,data:rWLbxVawHbg6Yty+zUpOaWiE0JLD694lkHGaUhoSraI=,iv:cOjr7PtJRj+McrEC/UyXObWZyi8O5Y+kgjhCQjo9jbU=,tag:SmXybLELVUlX5ADnOqi0FA==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb2J3MVBVdmVzSzMxSnpU
        Rm9QNyszRS9zSUNwWU9nMFcweTBSWXhrVFg4ClMrR29DajBXYlZrMFJkS09xUThv
        Rkk4RDRqdGwyVUpEWmZ5ZWxDdW9KZEEKLS0tIFN1VXdKWDUwSVlSWURRaklhN3kx
        VHhsUmRkQ05MUHdPRWlkVDhUelNDR1kKTGUij9MhddhRAv/UGnwcAuZvRQ+t4jmB
        IB0m4gvyiKpAH+xIrsYOxh1i7X+alI6RjTV6VO1sPTq6IQwL8eFNgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-16T02:01:33Z"
  mac: ENC[AES256_GCM,data:1MM3hs3fOjDRXpbh1abJfgqy8t4oTpZsGF8Cbb+gCHRwP601Jy6hK7Jnc1f2pewHJ6+r70pYtAIAlQKlUy35Vse/j793NyucC0CR8qA6R0XSsbFiB0oG0p62yEz4tNBA9e7DbxjLfVhaSVMdO0lrdu3kZMSqd4X4vovTlr3fhVI=,iv:c/FwtECuBdJyQKvj5KhnXsKnkbkS+ppSSLP4P4hYzyE=,tag:/EPj+Ij47FuOQMzEmNReBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
