apiVersion: v1
kind: Secret
metadata:
  name: recyclarr
type: Opaque
stringData:
  SONARR_API_KEY: ENC[AES256_GCM,data:GVAvKuuwx1HCe0rX0u71Az02OMefqRUjypzY2VCwHLk=,iv:f4AD2onOCZICQ9P+q30dOC0f+OSQQm2X1sfoWtSIQIA=,tag:evhuhKjhcsWPGKSAfvqaYQ==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUFNtVzZXdlNEWDY4VEk4
        eThMSlhGbEdzUXNsamoyVmxWS1pvcG5LcVdrCjZJYVdKeElva2EvVWJ1emo5S2R1
        Q1pNR2dhTks3S2RVSjNWN3NxQ2JoVTQKLS0tIFl6YjMrSjVGNWdxdFU3eGpKaGpV
        N2NJUlhEOTR1eHlmc1BXcllYZ25lblUKxO+LCTXbwq/7fQf5BBVtSotXh3uw328g
        Ss8uqN9VderDTHDuGuX3c/29d7PI4QujNRyLyN1a375CKGdzEbP4xQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T21:57:44Z"
  mac: ENC[AES256_GCM,data:44xrf6SVpwQUdVbPTADu9mMLGDbYHb1Mzal6zQGpM5iEvZz18j1OvoFPNinRdqD2kRMZVqnR1d7x4hmzhD7sLz6x4lg2Sn4mxxCCu19vzOVs3u8jA0WC1VQtpg41zNGjhco1RMkVMQHMB2DuecsbM7J/Iu0eOgui+7fyaOdchzU=,iv:zpGa3C82tcvoAbor7a1laHWxek7/x/Iki1gq6ApvF2c=,tag:xjOKYxZfcth4T/NnCKEaXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
