apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-media-pvc
  namespace: longhorn
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
