apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-media
spec:
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Ti
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: longhorn-media-volume
