apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagster-cloud
spec:
  releaseName: dagster-cloud
  interval: 30m
  chart:
    spec:
      chart: dagster-cloud-agent
      version: ~1
      sourceRef:
        kind: HelmRepository
        name: dagster-cloud
