apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  storageClassName: csi-s3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  storageClassName: csi-s3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
