apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard
  template:
    metadata:
      labels:
        app: adguard
    spec:
      initContainers:
      - name: readonly-conf-workaround
        image: busybox:1.32
        command: ["cp", "/tmp/AdGuardHome.yaml", "/opt/adguardhome/conf/AdGuardHome.yaml"]
        volumeMounts:
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
        - name: adguard-conf-secret
          mountPath: /tmp
      containers:
      - name: adguard-home
        image: adguard/adguardhome:latest
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 80
          name: web
          protocol: TCP
        volumeMounts:
        - name: adguard-data
          mountPath: /opt/adguardhome/work
        - name: adguard-conf
          mountPath: /opt/adguardhome/conf
      volumes:
      - name: adguard-data
        persistentVolumeClaim:
          claimName: adguard-data-pvc
      - name: adguard-conf
        persistentVolumeClaim:
          claimName: adguard-conf-pvc
      - name: adguard-conf-secret
        secret:
          secretName: adguard-secret
