apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguard
commonLabels:
  app.kubernetes.io/name: adguard
  app.kubernetes.io/part-of: smart-home-system
  app.kubernetes.io/component: dns-filter
resources:
  - namespace.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
