apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  url: oci://quay.io/jetstack/charts/cert-manager
  ref:
    semver: ~1
