apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  image: registry.k8s.io/external-dns/external-dns
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: external-dns
  namespace: external-dns
spec:
  imageRepositoryRef:
    name: external-dns
  policy:
    semver:
      range: ~0
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: default
  namespace: external-dns
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(external-dns): update image versions to {{ range .Changed.Changes }}{{ .NewValue }} {{ end }}
    push:
      branch: image-update-external-dns
