apiVersion: v1
kind: Namespace
metadata:
  name: kgateway-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kgateway
  namespace: kgateway-system
spec:
  type: oci
  interval: 5m
  url: oci://cr.kgateway.dev/kgateway-dev/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
  namespace: kgateway-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kgateway-crds
      version: 'v2.1.1'
      sourceRef:
        kind: HelmRepository
        name: kgateway
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
  namespace: kgateway-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kgateway
      version: 'v2.1.1'
      sourceRef:
        kind: HelmRepository
        name: kgateway
  values:
    agentgateway:
      enabled: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http
  namespace: kgateway-system
  annotations:
    cert-manager.io/issuer: letsencrypt-http
spec:
  gatewayClassName: kgateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.southcity.dev"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: letsencrypt-http-issuer-account-key
            kind: Secret
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-http
  namespace: kgateway-system
spec:
  acme:
    email: letsencrypt.chaps970@passmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-http-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
