apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./identity/pocket-id
  - ./network/cert-manager/
  - ./network/external-dns/
  - ./network/gateway-api/
  - ./network/kgateway/
  - ./network/metallb/
  - ./observability
  - ./reloader
  - ./security/kubelet-serving-cert-approver
  - ./storage/csi-driver-nfs
  - ./storage/csi-s3
  - ./storage/longhorn
