apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - longhorn.yaml
  - metallb.yaml
  - monitoring.yaml
  - nginx-fabric.yaml
  - pocket-id.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: dashboards
    namespace: cert-manager
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - ./dashboards/cert-manager.json
  - name: dashboards
    namespace: metallb
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - ./dashboards/metallb.json
  - name: dashboards
    namespace: longhorn-system
    options:
      labels:
        grafana_dashboard: "1"
    files:
      - ./dashboards/longhorn.json
