apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-encryption
  namespace: pocket-id
type: Opaque
stringData:
  encryption-key: ENC[AES256_GCM,data:zA8u+W9B/Mrjss+j94R7hNhG3xgo8nkps+BJiUP1sdzofUcLDVEiHwfGSkY=,iv:Lj95OwONc5M6uttJorFzWza9Hob2nMpYcc49dOkFCL4=,tag:3ACyIbFCpg2qbrzHelWIqw==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVEhvV055Zk9nL2dDeDB4
        MUNOWVZ3RHJYRW1UaGJ6VnoyS3FEZ2ErY3ljCllpM1FDb2plSlBvcWRudU1CT0U0
        OW5EUlJ0M0pmSllQdkRFNDF3YVNnc2MKLS0tIHVoUit3NmJPRTdwMHhKdlBUV1NF
        eWMwZm9wRHZjZTlsSVlDemkrN1dhbmsKPr8Hmw5j8MDNVeRqo0S4vGtyyxfL0P84
        Ko9yN7Yk6G+ysirYOcS4Jd/BeQkFYvwofIO+U0dYJuK13hI28Ty/FA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-08T14:18:41Z"
  mac: ENC[AES256_GCM,data:iCCPv1K5e9yEAj61DApG2oRtZFL9WmoyS8d/Q2Y1laMtRHc1uTXK0P0ynSkccUjNFDgsbGPxdxWRLbyx9CVgNhFx9Jl8sf/svlt9LdxHmi3dpamQF5eFWH9GtaDCOI9lub4bRHIKsG09wwasqXH8EqqXok9kce8Zuv6aIPkR2hs=,iv:/5P4T/URv6m68vHWvNpHJ/0EHgJ7x/qEibsU8elTsrw=,tag:O5KUGLBlVQ93ymCDhyvs3Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
