apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  image: ghcr.io/pocket-id/pocket-id
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  imageRepositoryRef:
    name: pocket-id
  policy:
    semver:
      range: ~2
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: default
  namespace: pocket-id
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(pocket-id): update image versions to {{ range .Changed.Changes }}{{ .NewValue }} {{ end }}
    push:
      branch: image-update-pocket-id
