apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky
  namespace: blocky
  labels:
    app.kubernetes.io/name: blocky
data:
  config.yml: |
    upstreams:
      groups:
        default:
          - 1.1.1.1
          - 1.0.0.1
          - 2606:4700:4700::1111
          - 2606:4700:4700::1001

    blocking:
      denylists:
        ads:
          - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/ultimate.txt
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      clientGroupsBlock:
        default:
          - ads
    ports:
      dns: 53
      http: 4000

    log:
      level: error

    prometheus:
      enable: true
      path: /metrics

    caching:
      prefetching: true
