---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: blocky
  namespace: blocky
spec:
  image: spx01/blocky
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: blocky
  namespace: blocky
spec:
  imageRepositoryRef:
    name: blocky
  policy:
    semver:
      range: v0.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: default
  namespace: blocky
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(blocky): update image versions to {{ join ", " (pluck "NewValue" .Changed.Changes) }}
    push:
      branch: main
