apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blocky
resources:
  - config.yaml
  - deployment.yaml
  - monitoring.yaml
  - namespace.yaml
  - service.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: dashboards
    namespace: blocky
    options:
      labels:
        app.kubernetes.io/name: blocky
        grafana_dashboard: "1"
    files:
      - ./dashboards/blocky.json
