apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: blocky
  labels:
    app.kubernetes.io/name: blocky
  annotations:
    metallb.io/loadBalancerIPs: 10.0.30.194
spec:
  selector:
    app.kubernetes.io/name: blocky
  type: LoadBalancer
  ports:
  - name: dns-udp
    port: 53
    targetPort: dns-udp
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: dns-tcp
  - name: prometheus
    port: 4000
    targetPort: prometheus
    protocol: TCP
