apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data-pvc
  namespace: pihole
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dns-pvc
  namespace: pihole
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
