apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  servar.app: jellyfin

configMapGenerator:
- name: jellyfin-conf
  literals:
  - PUID=1000
  - PGID=1000
  - TZ=Europe/Oslo

resources:
- pvc.yml
- deployment.yml
- service.yml
