apiVersion: v1
kind: Service
metadata:
  name: jellyfin-web
spec:
  type: LoadBalancer
  ports: 
  - name: web
    protocol: TCP
    port: 8096
    targetPort: web
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-local-discovery
spec:
  type: LoadBalancer
  ports: 
  - name: local-discovery
    protocol: TCP
    port: 7359
    targetPort: local-discovery
  - name: dlna
    protocol: TCP
    port: 1900
    targetPort: dlna
