apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
spec:
  interval: 30m
  releaseName: kgateway-crds
  chartRef:
    kind: OCIRepository
    name: kgateway-crds
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
spec:
  interval: 30m
  releaseName: kgateway
  chartRef:
    kind: OCIRepository
    name: kgateway
  values:
    agentgateway:
      enabled: true
