apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-data-pvc
  namespace: wireguard
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
