apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: homepage
  namespace: homepage
spec:
  image: ghcr.io/gethomepage/homepage
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: homepage
  namespace: homepage
spec:
  imageRepositoryRef:
    name: homepage
  policy:
    semver:
      range: ~1
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: default
  namespace: homepage
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(homepage): update image versions to {{ range .Changed.Changes }}{{ .NewValue }} {{ end }}
    push:
      branch: main
