apiVersion: v1
kind: Secret
metadata:
  name: pocket-id-encryption-key
type: Opaque
stringData:
  encryption-key: ENC[AES256_GCM,data:uTnQXzW59szUR6JcXNguzEzbpMNV8HTxqJrwFBvrxjiHPOK/CJxfj/XrsZg=,iv:iBRvgj/d/545UldVaPeEKG03iaW2IJQiZ/flyKHvTSs=,tag:yOPEzX0AZlLx8h+OSykS+g==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaUhhanZSUkJLd0I5TTU5
        T3RqVlh5NC9XUzgxTnVPYlptV3FhY3hWYVJ3Cmhna0dPanpYMjFiUGhvRGwwUmlO
        Q0ZDc1huV2ZxanZpdCtVa2JDUy9HcUkKLS0tIFUreUpIWG14T0tHS0ZzOSs2dndG
        TWVBVTFwLzVHeXBsZlBTZy9DT29LaG8K997h+EYN/n6RUiSzS9tGqJ3jfRGHuxDm
        pl6PXAzq3693C9BaPfHnrZLDlT9kfxWbSuj2stm60gJTkilopkwK9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T12:53:01Z"
  mac: ENC[AES256_GCM,data:JsTb4y6Z2AKndA3XurAsn9UpfTDsFVwwDMQlf6GTv84KdmMQd+kUAOnOf3sf6tZyqFJKs0xlHqSm2ldI/c4JkGyESG2g1AOhhVEfY1WQYy0mtNzQrUVaVFyZaRY18u4udL72oB2d5Z8NeTbj0bquiBldBtqMAJ2I1wcIQU8PFQw=,iv:FsxSyJoapNLKmAxTPq5rSX+WB41Lr6YA22ByHoWKVbA=,tag:kBlwu6fYrbDJhurtuLeKbg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
