apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 84.0.1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  serviceAccountName: flux
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  install:
    crds: Create
    timeout: 10m
  upgrade:
    crds: CreateReplace
    timeout: 10m
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - /metadata/annotations/prometheus-operator-validated
        target:
          kind: PrometheusRule
  values:
    alertManager:
      enabled: false
    grafana:
      defaultDashboardsEnabled: false
      adminPassword: flux
      route:
        main:
          enabled: true
          annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: Grafana
            gethomepage.dev/group: Cluster Management
            gethomepage.dev/description: Monitoring and Visualizations
            gethomepage.dev/icon: grafana.png
            gethomepage.dev/pod-selector: ""
          parentRefs:
            - name: http
              namespace: gateway-system
          hostnames:
            - "grafana.southcity.dev"
