apiVersion: mirror.fluxcd.io/v1alpha1
kind: Config
charts:
  - name: external-dns
    source: https://kubernetes-sigs.github.io/external-dns/
    destination: oci://ghcr.io/ssouthcity/homelab/mirrors/oci/external-dns
    version: ">=1.15.0"
    limit: 3
artifacts:
  - source: registry.k8s.io/external-dns/external-dns
    destination: ghcr.io/ssouthcity/homelab/mirrors/image/external-dns
    selector:
      semver: ">=0.15.0"
      limit: 3
    includeReferrers: true
