apiVersion: mirror.fluxcd.io/v1alpha1
kind: Config
charts:
  - name: alloy
    source: https://grafana.github.io/helm-charts
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
  - name: csi-driver-nfs
    source: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
  - name: csi-s3
    source: https://yandex-cloud.github.io/k8s-csi-s3/charts
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
  - name: dagster
    source: https://dagster-io.github.io/helm
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
  - name: external-dns
    source: https://kubernetes-sigs.github.io/external-dns/
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
  - name: kube-prometheus-stack
    source: https://prometheus-community.github.io/helm-charts
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
  - name: lakekeeper
    source: https://lakekeeper.github.io/lakekeeper-charts/
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
  - name: loki
    source: https://grafana.github.io/helm-charts
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
  - name: longhorn
    source: https://charts.longhorn.io
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
  - name: metallb
    source: https://metallb.github.io/metallb
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
  - name: metrics-server
    source: https://kubernetes-sigs.github.io/metrics-server/
    destination: oci://ghcr.io/ssouthcity/homelab/mirror/charts
    limit: 3
artifacts:
  # OCI Helm Charts
  - source: ghcr.io/aclerici38/charts/pocket-id-operator
    destination: ghcr.io/ssouthcity/homelab/mirror/charts/pocket-id-operator
    selector:
      limit: 3
    includeReferrers: true
  - source: ghcr.io/controlplaneio-fluxcd/charts/flux-operator
    destination: ghcr.io/ssouthcity/homelab/mirror/charts/flux-operator
    selector:
      limit: 3
    includeReferrers: true
  - source: ghcr.io/controlplaneio-fluxcd/charts/flux-operator-mcp
    destination: ghcr.io/ssouthcity/homelab/mirror/charts/flux-operator-mcp
    selector:
      limit: 3
    includeReferrers: true
  - source: cr.kgateway.dev/kgateway-dev/charts/kgateway
    destination: ghcr.io/ssouthcity/homelab/mirror/charts/kgateway
    selector:
      limit: 3
    includeReferrers: true
  - source: cr.kgateway.dev/kgateway-dev/charts/kgateway-crds
    destination: ghcr.io/ssouthcity/homelab/mirror/charts/kgateway-crds
    selector:
      limit: 3
    includeReferrers: true
  - source: quay.io/jetstack/charts/cert-manager
    destination: ghcr.io/ssouthcity/homelab/mirror/charts/cert-manager
    selector:
      limit: 3
    includeReferrers: true
  - source: ghcr.io/seerr-team/seerr/seerr-chart
    destination: ghcr.io/ssouthcity/homelab/mirror/charts/seerr
    selector:
      limit: 3
    includeReferrers: true
  - source: ghcr.io/stakater/charts/reloader
    destination: ghcr.io/ssouthcity/homelab/mirror/charts/reloader
    selector:
      limit: 3
    includeReferrers: true
  # Container Images (semver)
  - source: docker.io/gotson/komga
    destination: ghcr.io/ssouthcity/homelab/mirror/image/komga
    selector:
      limit: 3
    includeReferrers: true
  - source: ghcr.io/gethomepage/homepage
    destination: ghcr.io/ssouthcity/homelab/mirror/image/homepage
    selector:
      limit: 3
    includeReferrers: true
  - source: registry.k8s.io/external-dns/external-dns
    destination: ghcr.io/ssouthcity/homelab/mirror/image/external-dns
    selector:
      limit: 3
    includeReferrers: true
  - source: ghcr.io/recyclarr/recyclarr
    destination: ghcr.io/ssouthcity/homelab/mirror/image/recyclarr
    selector:
      limit: 3
    includeReferrers: true
  - source: docker.io/spx01/blocky
    destination: ghcr.io/ssouthcity/homelab/mirror/image/blocky
    selector:
      limit: 3
    includeReferrers: true
  - source: lscr.io/linuxserver/jellyfin
    destination: ghcr.io/ssouthcity/homelab/mirror/image/jellyfin
    selector:
      limit: 3
    includeReferrers: true
  - source: lscr.io/linuxserver/prowlarr
    destination: ghcr.io/ssouthcity/homelab/mirror/image/prowlarr
    selector:
      limit: 3
    includeReferrers: true
  - source: lscr.io/linuxserver/qbittorrent
    destination: ghcr.io/ssouthcity/homelab/mirror/image/qbittorrent
    selector:
      limit: 3
    includeReferrers: true
  - source: lscr.io/linuxserver/sonarr
    destination: ghcr.io/ssouthcity/homelab/mirror/image/sonarr
    selector:
      limit: 3
    includeReferrers: true
  - source: docker.io/qmcgaw/gluetun
    destination: ghcr.io/ssouthcity/homelab/mirror/image/gluetun
    selector:
      limit: 3
    includeReferrers: true
  - source: ghcr.io/home-assistant/home-assistant
    destination: ghcr.io/ssouthcity/homelab/mirror/image/home-assistant
    selector:
      sortBy: alphabetical
    includeReferrers: true
  - source: docker.io/josh5/unmanic
    destination: ghcr.io/ssouthcity/homelab/mirror/image/unmanic
    selector:
      limit: 3
    includeReferrers: true
