apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant
data:
  configuration.yaml: |
    default_config:

    frontend:

    http:
      use_x_forwarded_for: true
      trusted_proxies:
      - 10.0.0.0/8

    automation:

    script:

    scene:
---

