apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant
        securityContext:
          privileged: true
        ports:
        - name: web
          containerPort: 8123
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: home-manager
