apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/part-of: smart-home-system
  app.kubernetes.io/component: hub
resources:
- config.yaml
- deployment.yaml
- ingress.yaml
- namespace.yaml
- pvc.yaml
- service.yaml
