apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
spec:
  releaseName: seerr
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: seerr
  values:
    route:
      main:
        enabled: true
        hostnames:
          - seerr.southcity.dev
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Seerr
          gethomepage.dev/group: Media Server
          gethomepage.dev/description: Media request and discovery tool
          gethomepage.dev/icon: seerr.png
          gethomepage.dev/pod-selector: "app.kubernetes.io/instance=seerr"
        parentRefs:
          - name: http
            namespace: gateway-system
