apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagster
spec:
  values:
    dagster-user-deployments:
      deployments:
        - name: "iris-analysis"
          image:
            repository: "ssouthcity/iris_analysis"
            tag: v1
            pullPolicy: Always
          dagsterApiGrpcArgs:
            - "--python-file"
            - "/iris_analysis/definitions.py"
          port: 80
