apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/blocky
  - ../base/komga
  - ../base/dagster
patches:
  - path: dagster-values.yaml
    target:
      kind: HelmRelease
