apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  values:
    service:
      annotations:
        metallb.io/loadBalancerIPs: 10.0.30.193
      type: LoadBalancer
