apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data-pvc
  namespace: servarr
spec:
  storageClassName: longhorn
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
