apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: ssouthcity@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - dns01:
        cnameStrategy: Follow
        webhook:
          config:
            apiKeySecretRef:
              name: vercel-credentials
              key: token
            teamSlug: southcity-projects
          groupName: acme.rhythmbhiwani.in
          solverName: vercel
