apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-release
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: v1.x
      sourceRef:
        kind: HelmRepository
        name: cert-manager-charts
  values:
    installCRDs: true
