apiVersion: apps/v1
kind: Deployment
metadata:
  name: komga
  labels:
    app: komga
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komga
  template:
    metadata:
      labels:
        app: komga
    spec:
      containers:
        - name: komga
          image: gotson/komga:1.24.2 # {"$imagepolicy": "komga:komga"}
          ports:
            - name: http
              containerPort: 25600
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: komga
