apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: komga
  namespace: komga
spec:
  image: gotson/komga
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: komga
  namespace: komga
spec:
  imageRepositoryRef:
    name: komga
  policy:
    semver:
      range: ~1
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: default
  namespace: komga
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(komga): update image versions to {{ range .Changed.Changes }}{{ .NewValue }} {{ end }}
    push:
      branch: image-update-komga
