apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: komga
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Komga
    gethomepage.dev/group: Media Server
    gethomepage.dev/description: Comic Book Management
    gethomepage.dev/icon: komga.png
    gethomepage.dev/pod-selector: ""
spec:
  parentRefs:
    - name: http
      namespace: kgateway-system
  hostnames:
    - "komga.southcity.dev"
  rules:
    - backendRefs:
        - name: komga
          port: 25600
