apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:5.1.4 # {"$imagepolicy": "servarr:qbittorrent"}
          env:
            - name: PUID
              value: "1000"
            - name: GUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: WEBUI_PORT
              value: "8080"
            - name: TORRENTING_PORT
              value: "6881"
          ports:
            - name: http
              containerPort: 8080
            - name: torrent-tcp
              containerPort: 6881
              protocol: TCP
            - name: torrent-udp
              containerPort: 6881
              protocol: UDP
          volumeMounts:
            - name: qbittorrent
              mountPath: /config
            - name: media
              mountPath: /data/torrents
        - name: gluetun
          image: qmcgaw/gluetun:v3.41.1 # {"$imagepolicy": "servarr:gluetun"}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: gluetun-environment
          ports:
            - name: http-proxy
              containerPort: 8888
              protocol: TCP
            - name: shadowsocks-tcp
              containerPort: 8388
              protocol: TCP
            - name: shadowsocks-udp
              containerPort: 8388
              protocol: UDP
      volumes:
        - name: qbittorrent
          persistentVolumeClaim:
            claimName: qbittorrent
        - name: media
          nfs:
            server: 10.0.1.134
            path: /var/nfs/shared/Media_Server/torrents
