apiVersion: v1
kind: Secret
metadata:
  name: gluetun-environment
type: Opaque
stringData:
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:Etr8JYugTKs6,iv:LE9U6NqDRgcWnd20WPb7Jr452uG3Yf4TK3nZu5SaGdY=,tag:ue2QVYz+JwOV4NflS+kLmA==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:N8iE/CdVDpyf,iv:ukm169yiZGFxeXJCru9iFGdNHBhQp/AVDmAgYkB0lOg=,tag:csj6Hgk2iBrnjtkCdhj0+w==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:NPTQILVvR6OqAsi/QkJ6PBo7p5R1316ZbsMlzycw+QrFpQtDZzGNj2Ojtp8=,iv:gs4OaiE0h986w8FBkddXxROIoNAlfZ/Scy+/EvrMU3A=,tag:xamufLR00raID3cXPo9hSA==,type:str]
  VPN_PORT_FORWARDING: ENC[AES256_GCM,data:BcU=,iv:rz+YK3IBZmI6jM++wa6C80X3j8nxhi644wlC6osTtNs=,tag:mMVbdMaL8msiOVxeAImmuA==,type:str]
  PORT_FORWARD_ONLY: ENC[AES256_GCM,data:gOQ=,iv:8H3Mam9FVdFpyWV+uV7ioWJUKJhmc8SYaKciME36ebs=,tag:VWcvR+P0ltfWBsqUMEFRlg==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ckZjUEh3b2NYMzFSVGtX
        NC9Ga3FIbEd6clJqRFU5aGQ4WXQ5Zk9UZkZjCmJXbkFSc3dacmptNnRMdEphbmdV
        S0ZsMHcxcWFJUXd0R2V2c3B4ZnM5TGcKLS0tIEJwOXpvQkZRQ3hxdGdnZjM0VUd6
        TDBPVFQ4b2lsSDVySk1aZ05VUEtMMUUK17jWK226LCSXg9wrNhb5qw+j33wCbPmO
        mwXVLntnWlzosVC1qo3Uv3f/DeiaFo33DRKciZMMDhQAe+JNtLZ5Xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-23T21:57:44Z"
  mac: ENC[AES256_GCM,data:Buccp8hBCpLjVbB4E8OJsVubvDsxjxgCmOQSN8I3wa59LwfpZKsfbEvNKDslQnLTLUb4oBMzIGXYnLYX3mLySHUfuXGZ8rd+vub84oRtNu8Uu9ur1j8CuhRSQbL2clFRJLs8PpacYwK4ZEvicYlHYZMwUPlDKmeeGwDDc1pxIL4=,iv:v91wsre5YWVUyT99RDsZ7aVUPc0L3kDt4zwbLycz+PQ=,tag:FJ1E+TjJPq2BJSPnM/EVgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
