apiVersion: v1
kind: Secret
metadata:
  name: gluetun-environment
type: Opaque
stringData:
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:4IoEVp03mh00,iv:pNemD5ZQxplWxgHZZOW4KA5QwvV1SQWuB22g3k/ffXQ=,tag:L5k2ecjIeH5yGOVVWdIUIQ==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:01XXvipzi6Yx,iv:8PhNSo+eeCh5i3ACqtFqpXXJsbWc+JnWK3xPKv6afIk=,tag:kbGYvuEO2lbu0qCtMeQlyw==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:SDYpdWbJYNmCw02ZokKRcwMrySIjLu/fH0eXOwtB1+J2xiUr3dEeNDIAZtc=,iv:jtBwwh3g8hOqLvdSdKq77SuMq/UozkXQ7qUZqo4n/dM=,tag:PvV1gr/8eHpbgVRMNMobEw==,type:str]
  VPN_PORT_FORWARDING: ENC[AES256_GCM,data:fYc=,iv:pZGyXtIovsAUf6yPkgoM6SCIzKTVg4ecocynvOVuRW4=,tag:m7pK54JJETwsqa/sG/6BvQ==,type:str]
  PORT_FORWARD_ONLY: ENC[AES256_GCM,data:QRY=,iv:Hg/AZ6pR7ubYbpAgJFHyRCLyCAtBzFFPQ7k300kr4T4=,tag:gcPFXEL9mN9CfNeCrDC9Og==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS0RvVDMrRXNvRnFyemQ5
        T1JPb1c1MWhKcE5yOUZrTEpjZCtFdk9QZVdnCjFzNitzb011T3ZmYmxQdnN0OWFa
        QTRtczQ2bG1XWDJmK1IzTXBSY2hZRHcKLS0tIHhaTnV5Q3ZPbHozT3pFRjNRcFZ6
        L1E1V1hUbG1VOGRVN29TWVBiVjg0RXcKcJfXUaKoF390R5Kn8S6pAr1e/IxlVCMG
        qvBhEhoeA8tdxseRqKzMw52goSuGfIspHgJ//5E02K1FaUVY7J+0Kg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-27T04:07:21Z"
  mac: ENC[AES256_GCM,data:vih2v8LLwlcDS3qeZQOqoB8+vu+/yklKV4AAPZpEMUzhMWiixjbpmuzFF2yOsGjbGCJw7qCD/tk84gqdzSmsLxcDbFYE2Jnb7h5NbK5BN6XVgXkVOqt4gd71AecomCb4NNINOHfrDoWboJCmZ9xLNfDcBLqkwnNQ4iKLgqgRofk=,iv:fuJ+oLnXn6AOblAWGGATDgVQ8stXeqsh+IFuiW2ulRw=,tag:Wf0gWXAJhsnWuyvnFpZVMg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
