apiVersion: v1
kind: Secret
metadata:
  name: gluetun-environment
type: Opaque
stringData:
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:VrogqSGOMisy,iv:B1PoA8EjbqtfxE7CCs8bwFoYjrjZnGaspQukwslRX40=,tag:B+pLDvX9UFb8yXGi6HKm0Q==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:NVJuOg+KGSdL,iv:lC6Cam0oIRVy/Iu7crv5BRlNfjCTn8DiURXjs9wrcok=,tag:Wl5UdpraRTXL22LYCVhP5g==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:7C13UnAzklhZs+7c/x3LKLmG+oPZkR05zPvNLQynKRg5fuogRk3IemrJTYo=,iv:8lYxvO5LSEDkvVjLLPbkeQ2yIwUZeLavCvZGzes/OvM=,tag:ZuQEQ16gmyXqOpDHDqWOHA==,type:str]
  VPN_PORT_FORWARDING: ENC[AES256_GCM,data:yyQ=,iv:IDZCHbEpqdz3A8noQS8OMzwFpbgPDxydPVDLWsdt7g8=,tag:p4SWcOfa3ENsky2hqkNaHQ==,type:str]
  PORT_FORWARD_ONLY: ENC[AES256_GCM,data:Tvs=,iv:I0kQkJ1C3wYdNltfJL7FiKei8QKOs8cmH9eKYg2e7Iw=,tag:3Wwun6bqc3kQErV6wgSlgg==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV05DNVNnSlFoRHRlSHRQ
        dzU5b1hQaGxRYUVtUzhoVHFVa2x5MUtRaWdnCm1TNmJsaW1CT3ZSVnU5d0szWm9p
        Ni9kaWRRUldzcWg4MmtoMDJUTzZyQ00KLS0tIEM3ME1uSkc2dSt6OFc4eitPOEYv
        NE9SWjNhYnF0UFpkM3J3SzhIWElFWncKsmhHQ71kaUPOujAdYqY9UXefkL/b+sJi
        GdcIyHtbu+CYNVu+niOrmrseN93mB+DhBVYIdXdO4JSAiDlW5HAaXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-08T22:13:06Z"
  mac: ENC[AES256_GCM,data:5Qzkq7I62G1do6SMX4lTJoGH0s/yizvsdUbNub/7h7FG4edzqk5Pag610WdZkmo+M93DmOdtpc2CTaXEv3+9GcoO+LbgAMPDPHRndcGZa2h9bcrklWLcWBflkUAjf8R0Fv2ndjwyulPfMw9tdfItqkZSgqeoUnhAoJQCj3LQ2zU=,iv:J/TD2Sh1MBEkWgjsnjNLyUkEgbzJm9CpbqOvehPU6Io=,tag:JRXJjpwvTGROYTJGoeUqXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
