apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: qbittorrent
  namespace: servarr
spec:
  image: lscr.io/linuxserver/qbittorrent
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: qbittorrent
  namespace: servarr
spec:
  imageRepositoryRef:
    name: qbittorrent
  policy:
    semver:
      range: ~5
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: gluetun
  namespace: servarr
spec:
  image: qmcgaw/gluetun
  interval: 5h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: gluetun
  namespace: servarr
spec:
  imageRepositoryRef:
    name: gluetun
  policy:
    semver:
      range: ~3
