apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servarr
resources:
  - deployment.yaml
  - gluetun.secret.enc.yaml
  - image.yaml
  - pvc.yaml
  - route.yaml
  - service.yaml
