apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:latest"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - source-watcher
  cluster:
    type: kubernetes
    size: medium
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  sync:
    kind: OCIRepository
    url: "oci://flux-registry:5000/flux-cluster-sync"
    ref: "local"
    path: "./"
  kustomize:
    patches:
      - patch: |
          - op: add
            path: /spec/insecure
            value: true
        target:
          kind: OCIRepository
