apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
spec:
  repo: https://charts.longhorn.io
  chart: longhorn
  targetNamespace: longhorn-system
  createNamespace: true
  valuesContent: |-
    service:
      ui:
        type: LoadBalancer
