apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc
  namespace: monitoring
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:J11xSO50dlnZ3SlhJ9ky11FOhr2QcSq5NLnSgmhyT8qq1euq,iv:J0FBycs3WkiZNWqhfg82wur/oapzVZTELoMn+UWjtSw=,tag:fJFVAkaLSSdan4PUfeoGkg==,type:str]
  client_secret: ENC[AES256_GCM,data:ONHPAtOpXdHgI7fsV64SZGuj9zZJaga7IJ0ui6YcF0s=,iv:+w3C+ThT/+wGfoQ+MVABb3wzh23GToY/0vyuEqKec14=,tag:82NvpRcycRXe61u0AZlp3w==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdEdOc01QQmhFd3lWN1Bk
        d3QzakRTak1KQjVYVXhLeXdndzFWUUxlNDA0CjRUY0hKTmtqbi9IbXZOamFoWjlo
        c05XVXVGNkdYZngza0sxOHE5QUtrS1EKLS0tIERWQitwM0ZYdGhBZTJCdnJ2ajdD
        cTZ4ZzI5RUNiWjRRcFluY3N6ZmNnbHMKfMEHSrUQ4jMjxvnqJ/AgZyO9zllBcYlD
        SF2g3yq71AY8Ew5eiui5DWHa8tN/GwbpTv6EUerjmTSZyxBVCaU63g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T14:33:22Z"
  mac: ENC[AES256_GCM,data:xvXTU0VQjouygGseoIpHGFkE+J0bC7S3dhKNdH8MgSCnfutuemluQhGvj4zr6bXEklunhlSFJNAHmXi3abA/HNsno1U1MJFIUEDBRu6yILYAf6/1Ujzia/lrSoWeJ4CYswJFZUEgcxDtbKBT8RHd/KBpMyjYgxNBX+h18Anc3QA=,iv:QVwuMjRTvkHF9vhViWYMhuD3+gGWSZ0gkKUYlFluQ/A=,tag:SXJBDLML90RD5tIWcO7Hzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
