apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: grafana
spec:
  name: Grafana
  launchUrl: "https://grafana.southcity.dev"
  logoUrl: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/grafana.svg"
  callbackUrls:
    - "https://grafana.southcity.dev/login/generic_oauth"
  pkceEnabled: true
  allowedUserGroups:
    - name: grafana-admins
    - name: grafana-editors
    - name: grafana-viewers
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: grafana-admins
spec: {}
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: grafana-editors
spec: {}
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: grafana-viewers
spec: {}
