apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc
  namespace: monitoring
type: Opaque
stringData:
  client_id: ENC[AES256_GCM,data:0aB+Lp2qrIq8tuvI8ZAH3D9Y/TQRV7bNh1A3cQjeuyMw5GqN,iv:AErtH92EDDO5WvrC379BOM7Bfhv5k0jqdGW4BZyxcMY=,tag:wvzajrhi0O5CTfdHZU2hqw==,type:str]
  client_secret: ENC[AES256_GCM,data:2uM34GI2mh7mkeXxdHkgNiiuVjkp0gUExiw3rm1u6uY=,iv:icDhm8uDXnR0lTS2r7Je2J5CMxxwzKeJJpvzbLiXnoI=,tag:4VhoD04n3zec4qemP/qPWg==,type:str]
sops:
  age:
    - recipient: age1th32fhtm6wlmy824uwpsykwhe08ycj6nj5m8lvedfq5nwnz095ts93uzsm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT1FpTXFTb0NtMHptbjQ1
        dUNDKy9rSXVyNEJKL3d4ZDN1SWk4d0U0a2lNCkdESjYxNk1XSWpDZ2ZqRkNxbnov
        RHNIQVZEQjhsL3NsY0hKU1RiMGptTkkKLS0tIEY5MzJ1VDBBNnYzTVJhTGhFNE5P
        cjlOOGh0NFN2U1Roa2k2Q3ZJUlFLU0kK1Be6vzTVdNPBXxnbTvTPPUH4CU5BLERB
        WNedFHidWqnd51xvzCWFvh/38dPDJpcC+HA9bduLQWBaPYwXirmkWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-08T23:04:09Z"
  mac: ENC[AES256_GCM,data:duGq6xrI/OVsJwJRh8eOeyDJqccK1qAk6eshV3vpuVNboOAij7dCrEvmb/w4nfA/JFFC1LnEBkff5yJyJKUNGAycA/IaJigVhUUrv0Br8wDIJwQlfBBsi67qf5/xNUSZcplK8d+UV5hizJyrvm+k7KYRmGL7juxgYdBaZH3y814=,iv:M28wNqN1XvJN7iGQL3uZbpZ2N9aTvgYeNzJhSy2aGVY=,tag:b2LD/2l0aLOTWvpkn+GMUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
