apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    grafana:
      route:
        enabled: true
        parentRefs:
          - name: http
            namespace: kgateway-system
        hostnames:
          - "grafana.southcity.dev"
      grafana.ini:
        server:
          root_url: https://grafana.southcity.dev
        auth:
          disable_login_form: true
          oauth_auto_login: true
        auth.generic_oauth:
          enabled: true
          name: Pocket ID
          scopes: openid profile email groups
          auth_url: https://pocket-id.southcity.dev/authorize
          token_url: https://pocket-id.southcity.dev/api/oidc/token
          api_url: https://pocket-id.southcity.dev/api/oidc/userinfo
          use_pkce: true
          allow_sign_up: true
          role_attribute_path: contains(groups[*], 'admins') && 'Admin' || contains(groups[*], 'users') && 'Editor' || 'Viewer'
        panels:
          disable_sanitize_html: true
      envValueFrom:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
          secretKeyRef:
            name: grafana-oidc
            key: client_id
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
          secretKeyRef:
            name: grafana-oidc
            key: client_secret
