apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ~81
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    grafana:
      route:
        main:
          enabled: true
          annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: Grafana
            gethomepage.dev/group: Cluster Management
            gethomepage.dev/description: Monitoring and Visualizations
            gethomepage.dev/icon: grafana.png
            gethomepage.dev/pod-selector: ""
          parentRefs:
            - name: http
              namespace: kgateway-system
          hostnames:
            - "grafana.southcity.dev"
      grafana.ini:
        server:
          root_url: https://grafana.southcity.dev
        auth:
          disable_login_form: true
          oauth_auto_login: true
        auth.generic_oauth:
          enabled: true
          name: Pocket ID
          scopes: openid profile email groups
          client_id: ${CLIENT_ID}
          client_secret: ${CLIENT_SECRET}
          auth_url: ${AUTH_URL}
          token_url: ${TOKEN_URL}
          api_url: ${API_URL}
          signout_redirect_url: ${SIGNOUT_REDIRECT_URL}
          use_pkce: true
          allow_sign_up: true
          role_attribute_path: contains(groups[*], 'grafana-admins') && 'Admin' || contains(groups[*], 'grafana-editors') && 'Editor' || 'Viewer'
        panels:
          disable_sanitize_html: true
      envValueFrom:
        CLIENT_ID:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: client_id
        CLIENT_SECRET:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: client_secret
        AUTH_URL:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: authorization_url
        TOKEN_URL:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: token_url
        API_URL:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: userinfo_url
        SINGOUT_REDIRECT_URL:
          secretKeyRef:
            name: grafana-oidc-credentials
            key: end_session_url
