name: Publish Artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  publish-artifacts:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - monitoring
          - pocket-id
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Flux CLI
        uses: controlplaneio-fluxcd/distribution/actions/setup@3f1c0eb61da5f5249ca311b067d17347cd02bc51 # v2.8.6
      - name: Setup Cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
      - name: Login to Github Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push artifact
        uses: controlplaneio-fluxcd/distribution/actions/push@3f1c0eb61da5f5249ca311b067d17347cd02bc51 # v2.8.6
        id: push
        with:
          repository: ghcr.io/${{ github.repository }}/${{ matrix.component }}
          path: "./components/${{ matrix.component }}"
          diff-tag: latest
      - name: Sign artifact
        if: steps.push.outputs.pushed == 'true'
        run: cosign sign --yes $DIGEST_URL
        env:
          DIGEST_URL: ${{ steps.push.outputs.digest-url }}
  flux-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Flux CLI
        uses: controlplaneio-fluxcd/distribution/actions/setup@3f1c0eb61da5f5249ca311b067d17347cd02bc51 # v2.8.6
      - name: Setup Cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
      - name: Login to Github Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push immutable artifact
        id: push
        run: |
          output=$(flux push artifact \
            oci://ghcr.io/$REPOSITORY/manifests:$(git rev-parse --short HEAD) \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)@sha1:$(git rev-parse HEAD)" \
            --path="./" \
            --output=json)

          digest=$(echo $output | jq -r '.digest')
          echo "digest: $digest"
          echo "digest=$digest" >> $GITHUB_OUTPUT

          digest_url=$(echo $output | jq -r '. | .repository + "@" + .digest')
          echo "digest_url: $digest_url"
          echo "digest_url=$digest_url" >> $GITHUB_OUTPUT
        env:
          REPOSITORY: ${{ github.repository }}
      - name: Tag artifact as latest
        run: |
          flux tag artifact oci://$DIGEST_URL --tag latest
        env:
          DIGEST_URL: ${{ steps.push.outputs.digest_url }}
      - name: Sign artifact
        run: |
          cosign sign $DIGEST_URL
        env:
          DIGEST_URL: ${{ steps.push.outputs.digest_url }}
