name: publish-artifact
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  flux-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@5adad89dcce7b79f20274ae8e112bcec7bd46764 # v2.8.5
      - name: Setup Cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
      - name: Login to Github Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push immutable artifact
        id: push
        run: |
          digest=$(flux push artifact \
            oci://ghcr.io/$REPOSITORY/manifests:$(git rev-parse --short HEAD) \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)@sha1:$(git rev-parse HEAD)" \
            --path="./" \
            --output=json | jq -r '.digest')

          echo "digest=$digest" >> $GITHUB_OUTPUT
        env:
          REPOSITORY: ${{ github.repository }}
      - name: Tag artifact as latest
        id: tag-latest
        run: |
          digest=(flux tag artifact \
            oci://ghcr.io/$REPOSITORY/manifests@$DIGEST \
            --tag latest \
            --output=json | jq -r '.digest')

          echo "digest=$digest" >> $GITHUB_OUTPUT
        env:
          REPOSITORY: ${{ github.repository }}
          DIGEST: ${{ steps.push.outputs.digest }}
      - name: Sign artifact
        run: |
          cosign sign ghcr.io/$REPOSITORY/manifests@$DIGEST
          cosign sign ghcr.io/$REPOSITORY/manifests@$LATEST_DIGEST
        env:
          REPOSITORY: ${{ github.repository }}
          DIGEST: ${{ steps.push.outputs.digest }}
          LATEST_DIGEST: ${{ steps.tag-latest.outputs.digest }}
